### ISSUE TITLE
How to disable no action time range?

### ISSUE THREAD

**Issue by tjmcewan** [deragon/autopoweroff#25]
I'll just set it to 0 & 0 for now.  But potentially the system should handle commented config or explain how to disable each section? 🙏🏻

```
Exception in thread ApoObserver:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/share/python/modules/ApoObserverNoActionTimeRange.py", line 52, in run
    self.configuration.noactiontimerange[ApoConfig.ENDHOUR]:
TypeError: '<=' not supported between instances of 'NoneType' and 'NoneType'
```

Thanks again!

**Comment by deragon** [comment]
Fixed with commit https://github.com/deragon/autopoweroff/commit/5df355f6a12bd8fbfe8643d806d762be28d733b4.
